services:
  postgres:
    image: postgres:17-alpine
    container_name: report_export_container_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: report_export_db
    ports:
      - "5432:5432"
    volumes:
      - report_export_container_db_data:/var/lib/postgresql/data

volumes:
  report_export_container_db_data:
