services:
  postgres:
    image: postgres:17-alpine
    container_name: report_export_container_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: report_export_db
    ports:
      - "5432:5432"
    volumes:
      - report_export_container_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: reports-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - reports-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: reports-redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/db
    depends_on:
      - redis
    networks:
      - reports-network

volumes:
  report_export_container_db_data:
  redis_data:
  redis_insight_data:

networks:
  reports-network:
    driver: bridge
